[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RudeChat"
version = "1.0.0"
description = "RudeChat is a Python IRC client designed to be fast, portable, and fun. "
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
[project.scripts]
rudechat = "rudechat.main:main"
