[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RudeChat"
version = "4.2.0"
description = "Python IRC client designed to be fast, portable, and fun."
authors = [
    { name = "Irish" },
	{ name = "Bash Elliott", email="rackodo.business@gmail.com" }
]
license = { text = "GNU General Public License v3 (GPLv3)" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent"
]

[project.urls]
homepage = "https://github.com/ShrugShoulders/RudeChat"

[tool.setuptools]
packages = ["rudechat4"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"rudechat4" = [
    "DefaultConfig/*",
    "GUI/*",
    "Resources/*",
    "Resources/Splashes/*",
    "Resources/Fortunes/*",
    "Resources/Icons/*",
    "Resources/Macros/*",
    "Resources/Sounds/*",
    "Util/*",
    "Components/*",
    "Client/*",
]

[project.scripts]
rudechat = "rudechat4.__main__:__main__"