; .rudeconfig
[Presence]
auto_rejoin = True
auto_away_minutes = 30 ; if 0, then disabled
auto_join_invite = True

[Conversation]
replace_pronouns = False
use_emojis = True
tab_complete_terminator = :

[Visibility]
show_hostmask = True
use_time_stamp = True
minimize_to_tray = True

[Sounds]
use_beep_noise = True
custom_sounds = False

[Misc/Unknown]
display_user_modes = True
send_ctcp_response = True
auto_whois = False
auto_connect_to_networks = True

[Debugging]
logging = False