; .rudeserver
[General]
conn_name = Libera
conn_addr = irc.libera.chat
conn_port = 6697
conn_nick = Rude
conn_auth = 0 ; 0 = NickServ, 1 = SASL, 2 = ZNC
conn_ssl = True
conn_cert = False
conn_chans = #rudechat,##
conn_enabled = True

[NickServ]
nickserv_password = password

[SASL]
sasl_username = username
sasl_password = password

[ZNC]
znc_username = username
znc_password = password

