# Form implementation generated from reading ui file 'rude_gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 573)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.user_list.setGeometry(QtCore.QRect(710, 40, 91, 221))
        self.user_list.setMouseTracking(True)
        self.user_list.setAutoFillBackground(True)
        self.user_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.user_list.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.user_list.setItemAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.user_list.setObjectName("user_list")
        self.server_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.server_list.setGeometry(QtCore.QRect(710, 280, 91, 41))
        self.server_list.setObjectName("server_list")
        self.channel_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.channel_list.setGeometry(QtCore.QRect(710, 340, 91, 201))
        self.channel_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.channel_list.setBatchSize(250)
        self.channel_list.setItemAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.channel_list.setObjectName("channel_list")
        self.user_chan_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_chan_display.setGeometry(QtCore.QRect(7, 508, 101, 31))
        self.user_chan_display.setObjectName("user_chan_display")
        self.server_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.server_label.setGeometry(QtCore.QRect(710, 260, 81, 18))
        self.server_label.setObjectName("server_label")
        self.channel_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(710, 320, 81, 18))
        self.channel_label.setObjectName("channel_label")
        self.user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(710, 20, 81, 18))
        self.user_label.setObjectName("user_label")
        self.topic_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.topic_label.setGeometry(QtCore.QRect(0, 0, 791, 21))
        self.topic_label.setObjectName("topic_label")
        self.input_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(120, 510, 581, 32))
        self.input_text.setObjectName("input_text")
        self.display_text = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.display_text.setGeometry(QtCore.QRect(0, 20, 701, 481))
        self.display_text.setObjectName("display_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_chan_display.setText(_translate("MainWindow", "TextLabel"))
        self.server_label.setText(_translate("MainWindow", "TextLabel"))
        self.channel_label.setText(_translate("MainWindow", "TextLabel"))
        self.user_label.setText(_translate("MainWindow", "TextLabel"))
        self.topic_label.setText(_translate("MainWindow", "TextLabel"))
