import re

def replace_pronouns(text):
    """Replace gender-specific pronouns with gender-neutral pronouns"""
    phrases = {
        r'\bhis job\b': 'their job',
        r'\bher job\b': 'their job',
        r'\bhis car\b': 'their car',
        r'\bher car\b': 'their car',
        r'\bher house\b': 'their house',
        r'\bhis house\b': 'their house',
        r'\bhis friends\b': 'their friends',
        r'\bher friends\b': 'their friends',
        r'\bhis father\b': 'their father',
        r'\bher father\b': 'their father',
        r'\bhis mother\b': 'their mother',
        r'\bher mother\b': 'their mother',
        r'\bhis brother\b': 'their sibling',
        r'\bher brother\b': 'their sibling',
        r'\bhis sister\b': 'their sibling',
        r'\bher sister\b': 'their sibling',
        r'\bhis book\b': 'their book',
        r'\bher book\b': 'their book',
        r'\bhis phone\b': 'their phone',
        r'\bher phone\b': 'their phone',
        r'\bhis boss\b': 'their boss',
        r'\bher boss\b': 'their boss',
        r'\bhis teacher\b': 'their teacher',
        r'\bher teacher\b': 'their teacher',
        r'\bhis colleague\b': 'their colleague',
        r'\bher colleague\b': 'their colleague',
        r'\bhis advice\b': 'their advice',
        r'\bher advice\b': 'their advice',
        r'\bhis opinion\b': 'their opinion',
        r'\bher opinion\b': 'their opinion',
        r'\bher thoughts\b': 'their thoughts',
        r'\bhis thoughts\b': 'their thoughts',
        r'\bher thought\b': 'their thought',
        r'\bhis thought\b': 'their thought',
        r'\bhis bag\b': 'their bag',
        r'\bher bag\b': 'their bag',
        r'\bhis laptop\b': 'their laptop',
        r'\bher laptop\b': 'their laptop',
        r'\bhis friend\b': 'their friend',
        r'\bher friend\b': 'their friend',
        r'\bhis children\b': 'their children',
        r'\bher children\b': 'their children',
        r'\bhis child\b': 'their child',
        r'\bher child\b': 'their child',
        r'\bhis husband\b': 'their spouse',
        r'\bher husband\b': 'their spouse',
        r'\bhis wife\b': 'their spouse',
        r'\bher wife\b': 'their spouse',
        r'\bhis son\b': 'their child',
        r'\bher son\b': 'their child',
        r'\bhis daughter\b': 'their child',
        r'\bher daughter\b': 'their child',
        r'\bhis work\b': 'their work',
        r'\bher work\b': 'their work',
        r'\bhis project\b': 'their project',
        r'\bher project\b': 'their project',
        r'\bhis team\b': 'their team',
        r'\bher team\b': 'their team',
        r'\bhis manager\b': 'their manager',
        r'\bher manager\b': 'their manager',
        r'\bhis leader\b': 'their leader',
        r'\bher leader\b': 'their leader',
        r'\bhis mentor\b': 'their mentor',
        r'\bher mentor\b': 'their mentor',
        r'\bhis doctor\b': 'their doctor',
        r'\bher doctor\b': 'their doctor',
        r'\bhis health\b': 'their health',
        r'\bher health\b': 'their health',
        r'\bhis therapist\b': 'their therapist',
        r'\bher therapist\b': 'their therapist',
        r'\bhis story\b': 'their story',
        r'\bher story\b': 'their story',
        r'\bhis experience\b': 'their experience',
        r'\bher experience\b': 'their experience',
        r'\bhis problem\b': 'their problem',
        r'\bher problem\b': 'their problem',
        r'\bhis solution\b': 'their solution',
        r'\bher solution\b': 'their solution',
        r'\bhis client\b': 'their client',
        r'\bher client\b': 'their client',
        r'\bhis supervisor\b': 'their supervisor',
        r'\bher supervisor\b': 'their supervisor',
        r'\bhis partner\b': 'their partner',
        r'\bher partner\b': 'their partner',
        r'\bhis assistant\b': 'their assistant',
        r'\bher assistant\b': 'their assistant',
        r'\bhis keys\b': 'their keys',
        r'\bher keys\b': 'their keys',
        r'\bhis wallet\b': 'their wallet',
        r'\bher wallet\b': 'their wallet',
        r'\bhis watch\b': 'their watch',
        r'\bher watch\b': 'their watch',
        r'\bhis shoes\b': 'their shoes',
        r'\bher shoes\b': 'their shoes',
        r'\bhis perfume\b': 'their perfume',
        r'\bher perfume\b': 'their perfume',
        r'\bhis makeup\b': 'their makeup',
        r'\bher makeup\b': 'their makeup',
        r'\bhis hairstyle\b': 'their hairstyle',
        r'\bher hairstyle\b': 'their hairstyle',
        r'\bhis happiness\b': 'their happiness',
        r'\bher happiness\b': 'their happiness',
        r'\bhis sadness\b': 'their sadness',
        r'\bher sadness\b': 'their sadness',
        r'\bhis anger\b': 'their anger',
        r'\bher anger\b': 'their anger',
        r'\bhis love\b': 'their love',
        r'\bher love\b': 'their love',
        r'\bhis hobby\b': 'their hobby',
        r'\bher hobby\b': 'their hobby',
        r'\bhis sport\b': 'their sport',
        r'\bher sport\b': 'their sport',
        r'\bhis game\b': 'their game',
        r'\bher game\b': 'their game',
        r'\bhis music\b': 'their music',
        r'\bher music\b': 'their music',
        r'\bhis art\b': 'their art',
        r'\bher art\b': 'their art',
    }
      
    pronouns = {
        r'\bhe\b': 'they',
        r'\bhis\b': 'their',
        r'\bshe\b': 'they',
        r'\bher\b': 'their',
        r'\blads\b': 'folks',
        r'\blasses\b': 'folks',
    }
    
    # Replace specific phrases
    for pattern, replacement in phrases.items():
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    # Replace pronouns
    for pattern, replacement in pronouns.items():
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
        
    return text
