import re
import os

def replace_pronouns(text, channel=None):
    """Replace gender-specific pronouns with gender-neutral pronouns"""
    script_directory = os.path.dirname(os.path.abspath(__file__))
    filtered_channels_path = os.path.join(script_directory, 'filtered_channels.txt')

    active_channels = []
    if os.path.exists(filtered_channels_path):
        with open(filtered_channels_path, 'r') as file:
            # Read the file and strip any leading/trailing whitespace from each line
            active_channels = [line.strip() for line in file.readlines()]

    if channel in active_channels:
        phrases = {
            r'\bhis job\b': 'their job',
            r'\bher job\b': 'their job',
            r'\bhis car\b': 'their car',
            r'\bher car\b': 'their car',
            r'\bher house\b': 'their house',
            r'\bhis house\b': 'their house',
            r'\bhis friends\b': 'their friends',
            r'\bher friends\b': 'their friends',
            r'\bhis father\b': 'their father',
            r'\bher father\b': 'their father',
            r'\bhis mother\b': 'their mother',
            r'\bher mother\b': 'their mother',
            r'\bhis brother\b': 'their sibling',
            r'\bher brother\b': 'their sibling',
            r'\bhis sister\b': 'their sibling',
            r'\bher sister\b': 'their sibling',
            r'\bhis book\b': 'their book',
            r'\bher book\b': 'their book',
            r'\bhis phone\b': 'their phone',
            r'\bher phone\b': 'their phone',
            r'\bhis boss\b': 'their boss',
            r'\bher boss\b': 'their boss',
            r'\bhis teacher\b': 'their teacher',
            r'\bher teacher\b': 'their teacher',
            r'\bhis colleague\b': 'their colleague',
            r'\bher colleague\b': 'their colleague',
            r'\bhis advice\b': 'their advice',
            r'\bher advice\b': 'their advice',
            r'\bhis opinion\b': 'their opinion',
            r'\bher opinion\b': 'their opinion',
            r'\bher thoughts\b': 'their thoughts',
            r'\bhis thoughts\b': 'their thoughts',
            r'\bher thought\b': 'their thought',
            r'\bhis thought\b': 'their thought',
            r'\bhis bag\b': 'their bag',
            r'\bher bag\b': 'their bag',
            r'\bhis laptop\b': 'their laptop',
            r'\bher laptop\b': 'their laptop',
            r'\bhis friend\b': 'their friend',
            r'\bher friend\b': 'their friend',
            r'\bhis children\b': 'their children',
            r'\bher children\b': 'their children',
            r'\bhis child\b': 'their child',
            r'\bher child\b': 'their child',
            r'\bhis husband\b': 'their spouse',
            r'\bher husband\b': 'their spouse',
            r'\bhis wife\b': 'their spouse',
            r'\bher wife\b': 'their spouse',
            r'\bhis son\b': 'their child',
            r'\bher son\b': 'their child',
            r'\bhis daughter\b': 'their child',
            r'\bher daughter\b': 'their child',
            r'\bhis work\b': 'their work',
            r'\bher work\b': 'their work',
            r'\bhis project\b': 'their project',
            r'\bher project\b': 'their project',
            r'\bhis team\b': 'their team',
            r'\bher team\b': 'their team',
            r'\bhis manager\b': 'their manager',
            r'\bher manager\b': 'their manager',
            r'\bhis leader\b': 'their leader',
            r'\bher leader\b': 'their leader',
            r'\bhis mentor\b': 'their mentor',
            r'\bher mentor\b': 'their mentor',
            r'\bhis doctor\b': 'their doctor',
            r'\bher doctor\b': 'their doctor',
            r'\bhis health\b': 'their health',
            r'\bher health\b': 'their health',
            r'\bhis therapist\b': 'their therapist',
            r'\bher therapist\b': 'their therapist',
            r'\bhis story\b': 'their story',
            r'\bher story\b': 'their story',
            r'\bhis experience\b': 'their experience',
            r'\bher experience\b': 'their experience',
            r'\bhis problem\b': 'their problem',
            r'\bher problem\b': 'their problem',
            r'\bhis solution\b': 'their solution',
            r'\bher solution\b': 'their solution',
            r'\bhis client\b': 'their client',
            r'\bher client\b': 'their client',
            r'\bhis supervisor\b': 'their supervisor',
            r'\bher supervisor\b': 'their supervisor',
            r'\bhis partner\b': 'their partner',
            r'\bher partner\b': 'their partner',
            r'\bhis assistant\b': 'their assistant',
            r'\bher assistant\b': 'their assistant',
            r'\bhis keys\b': 'their keys',
            r'\bher keys\b': 'their keys',
            r'\bhis wallet\b': 'their wallet',
            r'\bher wallet\b': 'their wallet',
            r'\bhis watch\b': 'their watch',
            r'\bher watch\b': 'their watch',
            r'\bhis shoes\b': 'their shoes',
            r'\bher shoes\b': 'their shoes',
            r'\bhis perfume\b': 'their perfume',
            r'\bher perfume\b': 'their perfume',
            r'\bhis makeup\b': 'their makeup',
            r'\bher makeup\b': 'their makeup',
            r'\bhis hairstyle\b': 'their hairstyle',
            r'\bher hairstyle\b': 'their hairstyle',
            r'\bhis happiness\b': 'their happiness',
            r'\bher happiness\b': 'their happiness',
            r'\bhis sadness\b': 'their sadness',
            r'\bher sadness\b': 'their sadness',
            r'\bhis anger\b': 'their anger',
            r'\bher anger\b': 'their anger',
            r'\bhis love\b': 'their love',
            r'\bher love\b': 'their love',
            r'\bhis hobby\b': 'their hobby',
            r'\bher hobby\b': 'their hobby',
            r'\bhis sport\b': 'their sport',
            r'\bher sport\b': 'their sport',
            r'\bhis game\b': 'their game',
            r'\bher game\b': 'their game',
            r'\bhis music\b': 'their music',
            r'\bher music\b': 'their music',
            r'\bhis art\b': 'their art',
            r'\bher art\b': 'their art',
            r'\bhis glasses\b': 'their glasses',
            r'\bher glasses\b': 'their glasses',
            r'\bhis jacket\b': 'their jacket',
            r'\bher jacket\b': 'their jacket',
            r'\bhis coat\b': 'their coat',
            r'\bher coat\b': 'their coat',
            r'\bhis hat\b': 'their hat',
            r'\bher hat\b': 'their hat',
            r'\bhis medicine\b': 'their medicine',
            r'\bher medicine\b': 'their medicine',
            r'\bhis exercise\b': 'their exercise',
            r'\bher exercise\b': 'their exercise',
            r'\bhis diet\b': 'their diet',
            r'\bher diet\b': 'their diet',
            r'\bhis homework\b': 'their homework',
            r'\bher homework\b': 'their homework',
            r'\bhis test\b': 'their test',
            r'\bher test\b': 'their test',
            r'\bhis grade\b': 'their grade',
            r'\bher grade\b': 'their grade',
            r'\bhis school\b': 'their school',
            r'\bher school\b': 'their school',
            r'\bhis university\b': 'their university',
            r'\bher university\b': 'their university',
            r'\bhis boyfriend\b': 'their partner',
            r'\bher boyfriend\b': 'their partner',
            r'\bhis girlfriend\b': 'their partner',
            r'\bher girlfriend\b': 'their partner',
            r'\bhis crush\b': 'their crush',
            r'\bher crush\b': 'their crush',
            r'\bhis ex\b': 'their ex',
            r'\bher ex\b': 'their ex',
            r'\bhis intern\b': 'their intern',
            r'\bher intern\b': 'their intern',
            r'\bhis subordinate\b': 'their subordinate',
            r'\bher subordinate\b': 'their subordinate',
            r'\bhis contractor\b': 'their contractor',
            r'\bher contractor\b': 'their contractor',
            r'\bhis fear\b': 'their fear',
            r'\bher fear\b': 'their fear',
            r'\bhis joy\b': 'their joy',
            r'\bher joy\b': 'their joy',
            r'\bhis grief\b': 'their grief',
            r'\bher grief\b': 'their grief',
            r'\bhis painting\b': 'their painting',
            r'\bher painting\b': 'their painting',
            r'\bhis sculpture\b': 'their sculpture',
            r'\bher sculpture\b': 'their sculpture',
            r'\bhis photography\b': 'their photography',
            r'\bher photography\b': 'their photography',
            r'\bhis celebration\b': 'their celebration',
            r'\bher celebration\b': 'their celebration',
            r'\bhis vacation\b': 'their vacation',
            r'\bher vacation\b': 'their vacation',
            r'\bhis trip\b': 'their trip',
            r'\bher trip\b': 'their trip',
            r'\bhis journey\b': 'their journey',
            r'\bher journey\b': 'their journey',
            r'\bhis toothbrush\b': 'their toothbrush',
            r'\bher toothbrush\b': 'their toothbrush',
            r'\bhis towel\b': 'their towel',
            r'\bher towel\b': 'their towel',
            r'\bhis backpack\b': 'their backpack',
            r'\bher backpack\b': 'their backpack',
            r'\bhis ring\b': 'their ring',
            r'\bher ring\b': 'their ring',
            r'\bhis aunt\b': 'their aunt',
            r'\bher aunt\b': 'their aunt',
            r'\bhis uncle\b': 'their uncle',
            r'\bher uncle\b': 'their uncle',
            r'\bhis cousin\b': 'their cousin',
            r'\bher cousin\b': 'their cousin',
            r'\bhis niece\b': 'their niece',
            r'\bher niece\b': 'their niece',
            r'\bhis nephew\b': 'their nephew',
            r'\bher nephew\b': 'their nephew',
            r'\bhis grandparent\b': 'their grandparent',
            f'\bher grandparent\b': 'their grandparent',
            r'\bhis nurse\b': 'their nurse',
            r'\bher nurse\b': 'their nurse',
            r'\bhis coworker\b': 'their coworker',
            r'\bher coworker\b': 'their coworker',
            r'\bhis employee\b': 'their employee',
            r'\bher employee\b': 'their employee',
            r'\bhis course\b': 'their course',
            r'\bher course\b': 'their course',
            r'\bhis lecture\b': 'their lecture',
            r'\bher lecture\b': 'their lecture',
            r'\bhis professor\b': 'their professor',
            r'\bher professor\b': 'their professor',
            r'\bhis dream\b': 'their dream',
            r'\bher dream\b': 'their dream',
            r'\bhis goal\b': 'their goal',
            r'\bher goal\b': 'their goal',
            r'\bhis plan\b': 'their plan',
            r'\bher plan\b': 'their plan',
            r'\bI didn\'t believe her\b': 'I didn\'t believe them',
            r'\bI didn\'t believe him\b': 'I didn\'t believe them',
            r'\bI couldn\'t believe her\b': 'I couldn\'t believe them',
            r'\bI couldn\'t believe him\b': 'I couldn\'t believe them',
            r'\bI don\'t believe her\b': 'I don\'t believe them',
            r'\bI don\'t believe him\b': 'I don\'t believe them',    
            r'\bhe gave her\b': 'they gave them',
            r'\bhe gave him\b': 'they gave them',
            r'\bhe told her\b': 'they told them',
            r'\bhe told him\b': 'they told them',
            r'\bI saw her\b': 'I saw them',
            r'\bI saw him\b': 'I saw them',
            r'\bI helped her\b': 'I helped them',
            r'\bI helped him\b': 'I helped them',
            r'\bI trusted her\b': 'I trusted them',
            r'\bI trusted him\b': 'I trusted them',
            r'\bI met her\b': 'I met them',
            r'\bI met him\b': 'I met them',
            r'\bI found her\b': 'I found them',
            r'\bI found him\b': 'I found them',
            r'\bshe called him\b': 'they called them',
            r'\bshe called her\b': 'they called them',
            r'\bI remembered her\b': 'I remembered them',
            r'\bI knew her\b': 'I knew them',
            r'\bI knew him\b': 'I knew them',
            r'\bshe gave him\b': 'they gave them',
            r'\bshe gave her\b': 'they gave them',
            r'\bhe saw her\b': 'they saw them',
            r'\bhe saw him\b': 'they saw them',
            r'\bshe trusted him\b': 'they trusted them',
            r'\bshe trusted her\b': 'they trusted them',
            r'\bhe trusted him\b': 'they trusted them',
            r'\bhe trusted her\b': 'they trusted them',
            r'\bI knew she\b': 'I knew they',
            r'\bI knew he\b': 'I knew they',
        }

        pronouns = {
            r'\bhe\b': 'they',
            r'\bhis\b': 'their',
            r'\bhim\b': 'them',
            r'\bhimself\b': 'themselves',
            r'\bshe\b': 'they',
            r'\bher\b': 'their',
            r'\bhers\b': 'theirs',
            r'\bherself\b': 'themselves',
            r'\blads\b': 'folks',
            r'\blasses\b': 'folks',
            r'\bman\b': 'person',
            r'\bwoman\b': 'person',
            r'\bmen\b': 'people',
            r'\bwomen\b': 'people',
            r'\bguys\b': 'folks',
            r'\bgals\b': 'folks',
            r'\bdude\b': 'person',
            r'\bdudette\b': 'person',
        }
        
        # Replace specific phrases
        for pattern, replacement in phrases.items():
            text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
        
        # Replace pronouns
        for pattern, replacement in pronouns.items():
            text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
            
        return text

    else:
        return text